# Generated by Django 5.2.5 on 2025-08-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_add_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
