# Generated by Django 5.2.5 on 2025-08-30 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('first_rating', 'First Rating'), ('rating_milestone_5', '5 Movies Rated'), ('rating_milestone_10', '10 Movies Rated'), ('rating_milestone_25', '25 Movies Rated'), ('rating_milestone_50', '50 Movies Rated'), ('rating_milestone_100', '100 Movies Rated'), ('first_watch', 'First Movie Watched'), ('watch_milestone_5', '5 Movies Watched'), ('watch_milestone_10', '10 Movies Watched'), ('watch_milestone_25', '25 Movies Watched'), ('watch_milestone_50', '50 Movies Watched'), ('watch_milestone_100', '100 Movies Watched'), ('first_list', 'First List Created'), ('list_milestone_3', '3 Lists Created'), ('list_milestone_5', '5 Lists Created'), ('first_comment', 'First Comment'), ('comment_milestone_5', '5 Comments'), ('comment_milestone_10', '10 Comments'), ('comment_milestone_25', '25 Comments'), ('comment_milestone_50', '50 Comments'), ('points_milestone_100', '100 Points'), ('points_milestone_250', '250 Points'), ('points_milestone_500', '500 Points'), ('points_milestone_1000', '1000 Points'), ('level_1', 'Level 1'), ('level_2', 'Level 2'), ('level_3', 'Level 3'), ('level_4', 'Level 4'), ('level_5', 'Level 5'), ('level_6', 'Level 6'), ('level_7', 'Level 7'), ('level_8', 'Level 8')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='star', max_length=50)),
                ('color', models.CharField(default='#FFD700', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['badge_type'],
            },
        ),
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('total_after', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('movies_rated', models.PositiveIntegerField(default=0)),
                ('movies_watched', models.PositiveIntegerField(default=0)),
                ('lists_created', models.PositiveIntegerField(default=0)),
                ('comments_made', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Points',
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('action_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('user', 'action_type', 'action_id')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
